### ISSUE TITLE
Alpha state no longer makes sense

### ISSUE THREAD

**Issue by markushausammann** [ircmaxell/PHP-CryptLib#2]
Hi Anthony,

Now that CryptLib has been used as a basis for `\Zend\Crypt` and is linked from the ZF2 manual, I think you should at list publish it as a beta 1 or even stable. I understand that you would want users to use it at their own risk but it really doesn't make a good impression when users come here from the ZF manual and read that the software is in alpha while the framework they're using is stable. I just doesn't add up from a communication perspective IMO.

Regards,
Markus

**Comment by ircmaxell** [comment]
The problem with raising the bar, is that the encryptor parts are not finished. Since it's not feature complete (and there are still API changes needed), I don't feel comfortable upgrading it to beta status...

**Comment by markushausammann** [comment]
I understand. Maybe a clarification in the root readme would help people to have both the right trust and the right causion.
